# Generated by Django 4.0 on 2021-12-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(verbose_name='Ширина, мм')),
                ('height', models.IntegerField(verbose_name='Высота, мм')),
            ],
        ),
        migrations.CreateModel(
            name='PrintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('place', models.CharField(max_length=150, verbose_name='Место')),
                ('label_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='label_printer.label', verbose_name='Размер наклейки')),
            ],
        ),
    ]
