# Generated by Django 4.0 on 2021-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=15, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='printer',
            name='subnet_mask',
            field=models.CharField(default='255.255.255.0', max_length=15, verbose_name='Маска подсети'),
        ),
    ]
