# Generated by Django 4.0 on 2021-12-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0002_printer_ip_address_printer_subnet_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='ip_address',
            field=models.CharField(default='172.18.70.x', max_length=15, verbose_name='IP адрес'),
        ),
    ]
