# Generated by Django 4.0 on 2021-12-27 14:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0004_label_can_be_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='can_be_printed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DS сервера без QR', 'DS сервера без QR'), ('DS сервера с QR', 'DS сервера с QR'), ('Штрих код', 'Штрих код')], default='', max_length=43, verbose_name='Что может быть напечатано'),
        ),
    ]
