# Generated by Django 4.0 on 2022-05-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0005_alter_label_can_be_printed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='subnet_mask',
        ),
        migrations.AddField(
            model_name='printer',
            name='cups_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя в CUPS'),
            preserve_default=False,
        ),
    ]
